pipeline {
    agent any

    stages {
        stage('clone repository') {
            steps { 
            	echo 'checkout repository...'
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'git_credentials', url: 'https://github.com/Banjoman93/doctorpatients.git']]])
            	echo 'finished checkout repository...'
            	bat "dir"
            }
        }
        stage('Compile') {
        	steps {
        		echo "compiling.."
  					  	withMaven {
   				   			bat "mvn compile"
    					}
  			}	
        }
        stage('Test') {
            steps {
                bat "mvn test"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
